version: "3.9" # Docker Composeファイルのバージョンを指定
services:
  app: # サービス名は任意
    build: ./infra/php # ビルドコンテキスト(docker buildを実行する際のDockerfile が置かれている作業ディレクトリ)を指定
    volumes: # ホスト側のディレクトリや名前付きボリュームをコンテナ側へマウントしたい時に指定。今回はホスト側の ./backend ディレクトリをappサービスのコンテナ内 /work へマウント。
      - ./backend:/work

  web:
    image: nginx:1.20-alpine # 今回は公式のnginxイメージをそのまま利用。(Dockerfileは不要)
    ports: # nginxへ外(ホスト側)からコンテナ内へアクセスさせるため公開用のポートを設定。ホスト側:コンテナ側 と設定
      - 8080:80
    volumes: # ホスト側にあるディレクトリ、ファイルをコンテナ内へマウント
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work